// @ts-nocheck
import type React from "react";
import { ArrowRight, ChevronRight, Facebook, Instagram, MapPin, Menu, Phone, Star, Twitter, Youtube, Mail } from "lucide-react";
import { categories, gear, steps, benefits } from "@/data/homeData";
import Logo from "@/components/shared/Logo";
import GearCard from "@/components/shared/GearCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";

export default function HomePage() {
  return (
    <main className="min-h-screen overflow-hidden bg-white font-[Inter] text-[#1a1a2e]">
      {/* MARKER-MAKE-KIT-INVOKED */}
      <header className="sticky top-0 z-50 border-b border-slate-100 bg-white/95 shadow-[0_1px_8px_rgba(0,0,0,0.08)] backdrop-blur">
        <div className="mx-auto flex h-[70px] max-w-7xl items-center justify-between px-5 lg:px-8">
          <a href="#home" aria-label="GearUp home"><Logo /></a>
          <nav className="hidden items-center gap-7 lg:flex" aria-label="Primary navigation">
            {["Home", "Browse Gear", "Categories", "About Us", "Contact"].map((link) => <a key={link} href={`#${link.toLowerCase().replaceAll(" ", "-")}`} className="text-sm font-semibold text-[#1a1a2e] transition hover:text-[#e31824]">{link}</a>)}
          </nav>
          <div className="hidden items-center sm:flex"><a href="/login" className="rounded-lg bg-[#e31824] px-5 py-2.5 text-sm font-bold text-white transition hover:bg-[#c41520]">Log In</a></div>
          <details className="relative sm:hidden"><summary className="list-none rounded-lg p-2 text-[#1b2748]"><Menu className="size-6" /><span className="sr-only">Open navigation</span></summary><nav className="absolute right-0 top-12 w-56 rounded-xl border border-slate-100 bg-white p-3 shadow-xl">{["Home", "Browse Gear", "Categories", "About Us", "Contact"].map((link) => <a key={link} href={`#${link.toLowerCase().replaceAll(" ", "-")}`} className="block rounded-lg px-3 py-2.5 text-sm font-semibold hover:bg-red-50 hover:text-[#e31824]">{link}</a>)}</nav></details>
        </div>
      </header>

      <section id="home" className="relative flex min-h-[calc(90vh-70px)] items-center justify-center bg-[#1b2748] bg-[url('https://images.unsplash.com/photo-1551632811-561732d1e306?w=1800&auto=format&fit=crop&q=85')] bg-cover bg-center px-5 py-20 text-center before:absolute before:inset-0 before:bg-[#14203e]/78">
        <div className="relative z-10 mx-auto max-w-5xl">
          <p className="mx-auto inline-flex rounded-full bg-[#e31824] px-4 py-2 text-xs font-bold tracking-wide text-white sm:text-sm">🏕️ &nbsp;#1 Gear Rental Platform in Bangladesh</p>
          <h1 className="mt-6 text-4xl font-extrabold leading-[1.07] tracking-[-0.035em] text-white sm:text-6xl lg:text-7xl">Rent Premium Sports<br className="hidden sm:block" /> & Outdoor Gear</h1>
          <p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-200 sm:text-lg">Explore thousands of verified gear options. Book by the day, return when done — no commitment, just adventure.</p>
          <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="#featured-gear" className="inline-flex h-12 items-center justify-center gap-2 rounded-lg bg-[#e31824] px-6 text-sm font-bold text-white transition hover:bg-[#c41520]">Browse Gear Now <ArrowRight className="size-4" /></a><a href="#how-it-works" className="inline-flex h-12 items-center justify-center rounded-lg border border-white px-6 text-sm font-bold text-white transition hover:bg-white hover:text-[#1b2748]">How It Works</a></div>
          <div className="mx-auto mt-14 grid max-w-4xl grid-cols-2 divide-x divide-y divide-white/20 border-white/20 text-left sm:grid-cols-4 sm:divide-y-0 sm:text-center">
            {[["5,000+", "Gear Items"], ["1,200+", "Happy Customers"], ["300+", "Verified Providers"], ["50+", "Categories"]].map(([number, label]) => <div key={label} className="px-4 py-4"><p className="text-2xl font-extrabold text-white">{number}</p><p className="mt-1 text-xs font-medium uppercase tracking-[0.12em] text-slate-300">{label}</p></div>)}
          </div>
        </div>
      </section>

      <section id="categories" className="bg-[#f5f6fa] px-5 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#e31824]">Find your kit</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.025em] text-[#1b2748] sm:text-4xl">Browse by Category</h2></div><div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8">{categories.map(({ name, icon: Icon }) => <a key={name} href="#featured-gear" className="group flex min-h-38 flex-col items-center justify-center rounded-xl border border-transparent bg-white p-4 text-center shadow-sm transition hover:-translate-y-1 hover:border-[#e31824] hover:shadow-md"><Icon className="size-9 text-[#e31824] transition group-hover:scale-110" strokeWidth={1.8} /><span className="mt-3 text-sm font-bold leading-5 text-[#1b2748]">{name}</span></a>)}</div></div></section>

      <section id="featured-gear" className="px-5 py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#e31824]">Popular right now</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.025em] text-[#1b2748] sm:text-4xl">Top Gear This Week</h2><p className="mt-3 text-slate-500">Handpicked gear from our top-rated providers.</p></div><a href="#rent" className="hidden items-center gap-1 text-sm font-bold text-[#e31824] hover:underline md:inline-flex">View all gear <ChevronRight className="size-4" /></a></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{gear.map((item) => <GearCard key={item.name} item={item} />)}</div><a href="#rent" className="mx-auto mt-10 flex w-fit items-center gap-2 rounded-lg border border-[#e31824] px-6 py-3 text-sm font-bold text-[#e31824] transition hover:bg-red-50">View All Gear <ArrowRight className="size-4" /></a></div></section>

      <section id="how-it-works" className="bg-[#1b2748] px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-xl text-center"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-red-300">The simple way</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.025em] sm:text-4xl">Rent Gear in 4 Simple Steps</h2></div><div className="relative mt-14 grid gap-10 md:grid-cols-4 md:gap-5 before:absolute before:left-[12.5%] before:right-[12.5%] before:top-7 before:hidden before:border-t-2 before:border-dashed before:border-[#e31824] md:before:block">{steps.map(({ icon: Icon, title, text }, index) => <div key={title} className="relative z-10 text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-full border-4 border-[#1b2748] bg-[#e31824] text-lg font-extrabold">{index + 1}</div><Icon className="mx-auto mt-5 size-7 text-red-300" /><h3 className="mt-3 text-lg font-bold">{title}</h3><p className="mx-auto mt-2 max-w-56 text-sm leading-6 text-slate-300">{text}</p></div>)}</div></div></section>

      <section id="about-us" className="bg-[#f5f6fa] px-5 py-20"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#e31824]">Built for the outdoors</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.025em] text-[#1b2748] sm:text-4xl">Why Thousands Choose GearUp</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(({ icon: Icon, title, text }) => <Card key={title} className="rounded-xl bg-white p-6 shadow-sm"><div className="flex size-11 items-center justify-center rounded-lg bg-red-50"><Icon className="size-6 text-[#e31824]" /></div><h3 className="mt-5 text-lg font-bold text-[#1b2748]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></Card>)}</div></div></section>

      <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#e31824]">In their words</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.025em] text-[#1b2748] sm:text-4xl">What Our Customers Say</h2></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{[["JD", "John Doe", "Got a Trek mountain bike for the weekend — perfect condition, smooth process. Will definitely rent again!", "bg-blue-100 text-blue-700"], ["SM", "Sarah Miller", "Super easy checkout and the camping tent was exactly as described. My kids loved the camping trip!", "bg-pink-100 text-pink-700"], ["AK", "Alex Khan", "GearUp saved my ski trip at the last minute. Amazing service and quality gear from trusted providers.", "bg-emerald-100 text-emerald-700"]].map(([initials, name, quote, color]) => <Card key={name} className="rounded-xl border border-slate-100 bg-white p-7 shadow-[0_2px_12px_rgba(0,0,0,0.06)]"><p className="font-serif text-5xl leading-7 text-[#e31824]">“</p><div className="mt-4 flex gap-1">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className="size-4 fill-[#f4b740] text-[#f4b740]" />)}</div><p className="mt-5 leading-7 text-slate-600">{quote}</p><div className="mt-7 flex items-center gap-3"><span className={`flex size-10 items-center justify-center rounded-full text-sm font-extrabold ${color}`}>{initials}</span><span className="text-sm font-bold text-[#1b2748]">{name}</span></div></Card>)}</div></div></section>

      <section id="rent" className="relative overflow-hidden bg-[#e31824] px-5 py-20 text-center text-white"><div className="absolute -left-12 top-0 size-64 rounded-full border-[28px] border-white/10" /><div className="absolute -right-16 -bottom-28 size-72 rotate-45 border-[34px] border-white/10" /><div className="relative mx-auto max-w-3xl"><h2 className="text-3xl font-extrabold tracking-[-0.025em] sm:text-4xl">Ready to Gear Up for Your Next Adventure?</h2><p className="mt-4 text-lg text-red-100">Join 1,200+ adventurers who rent smart instead of buying.</p><a href="/register" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#1b2748] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#142060]">Start Renting Today <ArrowRight className="size-4" /></a></div></section>

      <footer id="contact" className="bg-[#1b2748] px-5 pt-16 text-white"><div className="mx-auto grid max-w-7xl gap-10 pb-12 sm:grid-cols-2 lg:grid-cols-4"><div><Logo inverse /><p className="mt-5 max-w-xs text-sm leading-6 text-slate-300">Rent sports and outdoor gear instantly. Adventure more, own less.</p><div className="mt-6 flex gap-3">{[Facebook, Instagram, Twitter, Youtube].map((Icon, index) => <a key={index} href="#contact" className="flex size-9 items-center justify-center rounded-full bg-white/10 text-red-300 transition hover:bg-[#e31824] hover:text-white"><Icon className="size-4" /></a>)}</div></div><div><h3 className="text-sm font-extrabold uppercase tracking-[0.12em]">Quick Links</h3><ul className="mt-5 space-y-3 text-sm text-slate-300">{["Home", "Browse Gear", "How It Works", "Pricing", "About Us"].map((text) => <li key={text}><a href="#home" className="hover:text-white">{text}</a></li>)}</ul></div><div><h3 className="text-sm font-extrabold uppercase tracking-[0.12em]">Categories</h3><ul className="mt-5 space-y-3 text-sm text-slate-300">{["Camping & Hiking", "Cycling", "Water Sports", "Winter Sports", "Fitness & Gym", "Rock Climbing"].map((text) => <li key={text}><a href="#categories" className="hover:text-white">{text}</a></li>)}</ul></div><div><h3 className="text-sm font-extrabold uppercase tracking-[0.12em]">Contact</h3><ul className="mt-5 space-y-4 text-sm text-slate-300"><li className="flex gap-3"><Mail className="mt-0.5 size-4 shrink-0 text-red-300" />support@gearup.com</li><li className="flex gap-3"><Phone className="mt-0.5 size-4 shrink-0 text-red-300" />+880 1700-000000</li><li className="flex gap-3"><MapPin className="mt-0.5 size-4 shrink-0 text-red-300" />Dhaka, Bangladesh</li></ul></div></div><div className="border-t border-white/15 py-6"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-center text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:text-left"><p>© 2025 GearUp. All rights reserved.</p><div className="flex justify-center gap-5"><a href="#privacy" className="hover:text-white">Privacy Policy</a><a href="#terms" className="hover:text-white">Terms of Service</a></div></div></div></footer>
    </main>
  );
}
